### ISSUE TITLE
Need for Assistance?

### ISSUE THREAD

**Issue by 1DanielG** [ttrodrigz/iterake#1]
Hi Tony
Sorry. I couldn't find your email address. Do you have a vintage or documentation for your package. I was looking for a package about rim weighting in R. I am happy to help with If you require any.

**Comment by ttrodrigz** [comment]
Hi Daniel!

This package is still in active development and still has a ways to go until it is ready to be used. (Shame on me for including installation instructions, got trigger-happy with the README.)

My collaborator (@dwitherell) and I aren't currently at the point where we are looking for assistance. However, once the package is in working order and some basic documentation is done, your assistance would be much appreciated. We intend on submitting this to CRAN, so comments/critiques on documentation and actually testing the package would be super helpful.

Feel free to reach out to me at ttrodrigz@gmail.com.

Tony

**Comment by ttrodrigz** [comment]
@1DanielG, wanted to reach back out and let you know that this package is in a fairly stable place and can be used. The README has been updated with an example of how to use it. The documentation that can be accessed via help() is up-to-date as well.

I know it's been a while, but if you were still interested in a package that will do rim weighting, give this one a shot! If you try it out, please let us know what you think.

Tony

**Comment by 1DanielG** [comment]
Hi Tony,

Thank you so much for the heads up.
Sure, I will give it a try as soon as I get a chance in the coming week. I
will keep you posted then :)

Cheers,
Ali
