### ISSUE TITLE
Error in universe: There are mismatches between the buckets provided, and the unique values of `data

### ISSUE THREAD

**Issue by Hadsga** [ttrodrigz/iterake#3]
I reinstall R and RStudio, so I have to reinstall your package. I had the version before.  Since this you have made some changes. How can I get the version before?

Before I could use characters now I have to use factors as bucket input which leads to some issues.

**Comment by dwitherell** [comment]
Hi @Hadsga - could you give a minimal reproducible example that shows the issue occurring? That should be all we need to take a look at what is going wrong and resolving the issue for you. Thanks!

**Comment by dwitherell** [comment]
@Hadsga we made some attempts to address things based on what we assumed was the issue - could you reinstall the newest version and try again, then let us know how it goes? Hopefully it fixes things up for you!

**Comment by Hadsga** [comment]
Sorry for my late reply. It works, thank you.

**Comment by dwitherell** [comment]
Hi @Hadsga - no worries, thanks for letting us know it works now!
