### ISSUE TITLE
Quite huge difference of one item result compared to cell weighting

### ISSUE THREAD

**Issue by meh-wzdech** [ttrodrigz/iterake#5]
Hello,

I'm new to R. I also don't know much about the details of raking. I just heard about it as an easier way to weight data (compared to cell weighting).

So, I installed your package. All results are very similar to those weighted cell by cell (differences usually do not exceed +/- 3 pp.). Sadly, in one case the difference is 8 pp.  Do you have any idea why? It was a simple frequency table for a multiple response set (generated in SPSS using `CTABLES`).

This is the code (but I think that concerning this issue it's not important much):
```
#loading libraries
library(foreign)
library(iterake)
library(expss)
library(haven)
library(labelled)
library(rstudioapi)

#raking universe
#the target base was 753 so I increased the N to reach it
uni = universe(data = df, category(name = "q1", 
                                   buckets = c("a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p"), 
                                   targets = c(0.0752,0.0544,0.0554,0.0262,0.0669,
                                                 0.0870,0.1427,0.0244,0.0535,0.0296,
                                                 0.0593,0.1198,0.0331,0.0362,0.0920,
                                                 0.0441), sum.1 = TRUE), 
                          category(name = "q2",
                                   buckets = c("a","b", "c","d"), 
                                   targets = c(0.1760,0.2406,0.3397,0.2437), sum.1 = TRUE), N = 844)

#creation of the raked dataframe
df.wgt = iterake(universe = uni)
```

Below you can find results of the question I'm speaking about:
```
CELL WEIGHT
item1      2%        2
item2      13%      14
item3      15%      17
item4      16%      18
item5      18%      21
item6      21%      24
item7      22%      25
**item8      41%      47**
TOTAL     148%    113

R WEIGHT
item1      2%        2
item2      15%      19
item3      15%      19
item4      17%      21
item5      19%      24
item6      21%      26
item7      24%      31
**item8      33%      42**
TOTAL     146%    126
```

If you helped to fix this problem in any way it would be **fantastic** because I find your package very useful.

Greetings,
Konrad

**Comment by ttrodrigz** [comment]
Hi Konrad,

Unfortunately without seeing a reproducible example it's going to be difficult to track down exactly where the difference is coming from. I don't know the data in your `df` object, and I don't know what you did to produce the weights with cell weighting. Though I would say this to start:

- Different weighting procedures are likely to produce different results, {iterake} uses iterative raking so there's no reason to believe that it will produce the same result as cell weighting.
- Be sure to check the input to `targets`, you have quite a lot of values in there and it's easy to make a typo! Make sure those values you enter match whatever you did for the other weighting procedure.

**Comment by meh-wzdech** [comment]
Hello,

thanks for an answer!

I will do my best to pass you a dataset. I need to ask for permission first, and second, _obfuscate_ it because it is from a commercial project :(. Thus, I would like to send it to you via other channel (e-mail or something) if you didn't mind.

Concerning the rest of your message:
- the problem is that your package for the rest of questions and its answers/items produced **very similar results**. That's why I would love to use it in the future because as you know cell weighting is exhausting. **Sadly**, a 8 pp. difference is too big to use {iterake} weights.

- I don't think those differences are due to my typo just because other results were pretty the same. After all, thanks for this advice. I'll review my data, syntaxes both in R and SPSS and let you know if I found any mistakes.
