### ISSUE TITLE
Iterake doesn't create weights and R is not showing any error

### ISSUE THREAD

**Issue by gazellica** [ttrodrigz/iterake#8]
Hi,

I am using the Iterake package and iterake function for iterative weighting in different survey results. And it works great. But now I have a problem with it and, since RStudio didn't show any error, I don't know what that could be.

I have a dataset "inp" with 22.000 observations (respondents) and 29 variables (four of them are variables that should be used in iterative weighting: gender (with values 1 and 2), age group (with values from 1 to 15, since there are 15 age groups), the third variable is the group that a respondent belongs to according to region (values from 1 to 8) and the fourth variable has values 1 and 2 (depending of the size of a households of a respondent). So I created these four columns in my sample dataset and calculated the same shares in the whole population.

The next step was to use the function universe to create uni:

uni <- universe(
          data = inp,
          category(name="rim1",
          buckets = c("1", "2"),
          targets = c(0.51, 0.49)
      ),
         category(name="rim2",
          buckets = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15"),
          targets = c(0.10, 0.06, 0,06, 0.07, 0.07, 0.07, 0.07, 0.08, 0.07, 0.07, 0.07, 0.06, 0.05, 0.05, 0.05)
      ), 
        category(name="rim3",
          buckets = c("1", "2", "3", "4", "5", "6", "7", "8"),
          targets = c(0.26, 0.10, 0.07, 0.08, 0.26, 0.09, 0.06, 0.08)
      ), 
       category(name="rim4",
          buckets = c("1", "2"),
          targets = c(0.22, 0.78)
      )
)

That step is working. It creates uni as a list.
The next step, that works with all the other surveys, doesn't work here, i.e. it starts working and never ends, without any errors showed:

inpw <- iterake(universe=uni, threshold = 0.0001, max.wgt=10, max.iter=50)

I tried also without all these arguments, and still the same.
Do you have any idea what could be the issue here? Any suggestion or help would be great.

Thanks for helping and thanks for such a good package, I use it every day. :)

Best regards,

Gordana

**Comment by dwitherell** [comment]
Hi Gordana -

Is the "inp" dataset similar in size/structure to other surveys you've used?

It's hard to know for sure without seeing the data, but my gut says the discrepancies between your targets and what is actually in the "inp" dataset are too large to easily resolve, hence the long processing time. You either need to increase your max.wgt to something larger than 10 (not ideal of course), or make the threshold a larger value (meaning larger summed differences will qualify as "complete") to get things to resolve quicker.

I am unsure as to the feasibility of it, but if possible a link to the data you are using would allow us to poke around and determine what exactly is driving the suddenly much much slower performance on this particular dataset.

Devon

**Comment by gazellica** [comment]
Hi, Devon
Thank you very much for your quick reply. Unfortunately, I can't give you a link to the data, since it is a file with confidential data on our company's server. But, while trying to run this iterative weighting, I made a subset of that dataset and now it contains only ID column and four columns (each for one of the variables I need for weighting process). These variables I already mentioned in my previous mail. The number of rows (observations) is 22.000. When I selected only 1.000 observations to try to work with smaller dataset, it worked. The iterake function provided me with weights, even if I didn't change any of the arguments. As soon as I put 2.000 instead of 1.000 of observations, it didn't work. The same problem again. Then I changed arguments (max.wgt=100, threshold=0.05), and still nothing. It works only if I have about 1.000 rows. Since my dataset has 22.000 rows, I don't know what to do. Could you give me your email, so I could maybe send you my dataset (without confidential data, only with the columns needed for weighting), since I am not able to find what could be the issue with the function that worked perfectly for me until this case?

Thank you for trying to help me 😊

Gordana

**Comment by dwitherell** [comment]
Hi Gordana -

I was thinking the same thing in terms of the data, just sending along the id and 4 columns so as to not violate any privacy laws - you can send it to devonwitherell@hotmail.com. I'd be happy to take a look and figure out what might be driving the strange behavior.

Thanks!

Devon
