### ISSUE TITLE
Putting miminum weight value

### ISSUE THREAD

**Issue by TinaVanRegenmortelIpsos** [ttrodrigz/iterake#9]
Hello,

I am using the "max.wgt" argument to cap the maximum weight when using iterake.
But was wondering if there is also a way to cap the minimum weight?

many thanks
Tina

**Comment by ttrodrigz** [comment]
Hi Tina, there is not currently a way of setting the minimum weight. 

Is this something you often find to be necessary? I don't have the paper in front of me at the moment, but based on the literature I've read small weights are not as consequential as very large weights. 

We are currently working on an updated version of this package, so if a minimum weight cap is something that you would find useful it's something we can look at adding.

**Comment by TinaVanRegenmortelIpsos** [comment]
Hi Tony,

thank you very much for your answer.
We have been calculating the weights for a couple of waves now for a client and they have never asked for a minimum to be set. But now, they are asking for a minimum value of 0.25.
If this is something you could add to your package, then that would be much appreciated of course!

Do you have any timings on when an updated version of the package might be available? Just so I know if I should be looking into other options to do the calculations for now.

Many thanks
Tina

**Comment by ttrodrigz** [comment]
Tina,

Understood, that is certainly something that we can add. 

One thing to note is that the restriction on the minimum weight could lead to the algorithm either (a) taking longer to converge - which is not really an issue, or (b) it may not converge at all - meaning that you'll likely need to loosen the threshold needed to converge.

> Do you have any timings on when an updated version of the package might be available?

We are hoping that we will have a stable version of this package done in the next couple of weeks with the goal to have it released on CRAN. But the development version of the package should be ready in a couple of weeks.

**Comment by TinaVanRegenmortelIpsos** [comment]
Hi Tony,

clear! Thank you. 
I will check with my client whether they can wait until then.
Could you let me know when the updated package is actually availabe?

Many thanks!
Tina

**Comment by ttrodrigz** [comment]
If you would like to try the latest development version, you can re-download/install now and give it a try. We do have a few different API changes that will break some of your existing code. Here's an example workflow (though this isn't the only way of doing it):

``` r
library(iterake)

# Build the universe, now with pipes!
uni <-
    mtcars |> 
    universe() |> 
    new_category(
        name = "vs",
        groups = c(0, 1),
        targets = c(0.52, 0.48)
    ) |> 
    new_category(
        name = "cyl",
        groups = c(4, 6, 8),
        targets = c(0.3, 0.2, 0.5)
    )

# Run iterake(), now can set both min and max weights
res <- iterake(
    universe = uni,
    permute = TRUE,
    control = control_iterake(
        threshold = 0.0001,
        max_weight = 3,
        min_weight = 0.1,
        max_stuck = 5,
        max_iter = 100
    )
)
#> \ 1/2 ETA:  0s | Permutations \ 2/2 ETA:  0s | Permutations 

print(res)
#> -- iterake ---------------------------------------------------------------------
#> 
#>       Status: Converged
#>   Iterations: 77
#> Unweighted N: 32.0
#>   Weighted N: 32.0
#>  Effective N: 28.4
#>   Efficiency: 88.9%
#>         Loss: 0.125
#>         Mean: 1.000
#>        Order: vs, cyl

# Check the statistics of the weights
weight_stats(res)
#> # A tibble: 1 x 9
#>   uwgt_n wgt_n eff_n  loss efficiency  mean median   min   max
#>    <int> <dbl> <dbl> <dbl>      <dbl> <dbl>  <dbl> <dbl> <dbl>
#> 1     32    32  28.4 0.125      0.889  1.00   1.14 0.114  1.47

# Extract the weights
extract_weights(res, name = ".weight", append = TRUE)
#> # A tibble: 32 x 12
#>      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb .weight
#>    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>   <dbl>
#>  1  21       6  160    110  3.9   2.62  16.5     0     1     4     4   0.176
#>  2  21       6  160    110  3.9   2.88  17.0     0     1     4     4   0.176
#>  3  22.8     4  108     93  3.85  2.32  18.6     1     1     4     1   0.949
#>  4  21.4     6  258    110  3.08  3.22  19.4     1     0     3     1   1.47 
#>  5  18.7     8  360    175  3.15  3.44  17.0     0     0     3     2   1.14 
#>  6  18.1     6  225    105  2.76  3.46  20.2     1     0     3     1   1.47 
#>  7  14.3     8  360    245  3.21  3.57  15.8     0     0     3     4   1.14 
#>  8  24.4     4  147.    62  3.69  3.19  20       1     0     4     2   0.949
#>  9  22.8     4  141.    95  3.92  3.15  22.9     1     0     4     2   0.949
#> 10  19.2     6  168.   123  3.92  3.44  18.3     1     0     4     4   1.47 
#> # i 22 more rows

# Obtain the weighting factors assigned to each group
weight_factors(res)
#> # A tibble: 5 x 4
#>      vs   cyl .weight     n
#>   <dbl> <dbl>   <dbl> <int>
#> 1     0     4   0.114     1
#> 2     0     6   0.176     3
#> 3     0     8   1.14     14
#> 4     1     4   0.949    10
#> 5     1     6   1.47      4
```

<sup>Created on 2024-03-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>



If you choose to try this development version and for some reason want or need to roll back to the older version, you can re-install it with `remotes::install_github("ttrodrigz/iterake@e5c04c8")` which will roll it back to an earlier commit.

**Comment by TinaVanRegenmortelIpsos** [comment]
Hi Tony,

thank you so much for the quick update!
This did take more time, but seemed to work like a charm!

**Comment by ttrodrigz** [comment]
That's great, glad to hear it. Please let us know if you have any other suggestions or ideas. We would be interested to know if there are any other features that users of this package would want.
